avatar:      http://s.gravatar.com/avatar/06d54a07c11d6be7513a7b05c78fe71f
title:       Harry.ZD
description:  java node.js and python hacker in jilin university 2010 @changchun I love girls!
delimiter:   "&nbsp;&nbsp;"
# domain:      http://joshtronic.com
email:       harryzd122456@gmail.com
# markdown:    rdiscount
permalink:   pretty
pygments:    true
username:    harryzd
